# Generated by Django 3.0.5 on 2021-07-26 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('fiat_budget', models.FloatField(default=0.0)),
                ('btc_budget', models.FloatField(default=0.0)),
                ('eth_budget', models.FloatField(default=0.0)),
                ('dot_budget', models.FloatField(default=0.0)),
                ('ada_budget', models.FloatField(default=0.0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=0.0)),
                ('choice', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('choise_crypto', models.CharField(choices=[('btc', 'btc'), ('ada', 'ada'), ('eth', 'eth'), ('dot', 'dot')], max_length=20)),
                ('prenotation', models.CharField(default=False, max_length=30)),
                ('order_close', models.BooleanField(blank=True, default=False)),
                ('date_executed', models.DateTimeField(auto_now_add=True)),
                ('profit', models.FloatField(default=0.0)),
                ('add_to_Wallet', models.BooleanField(blank=True, default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
